# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Scan target with CloudFail

on:
  workflow_dispatch:
    inputs:
      cloudfail_target:
        description: "Target Site"
        default: "cloudflare.com"
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install python3-setuptools
        pip install flake8
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
    - name: Scan target site with CloudFail
      run: |
        python3 cloudfail.py --update --target "${{ env.CLOUDFAIL_TARGET }}"
        
      env:
          CLOUDFAIL_TARGET: ${{ inputs.cloudfail_target }}
